meat_sub = ['seitan', 'tofu', 'jackfruit', 'tempeh', 'lentils', 'beans', 'plant-based chicken']

meat_list = ['bacon','cod','tilapia','beef', 'lamb', 'pork', 'fish', 'salmon', 'steak', 'chicken', 'turkey', 'duck', 'goose', 'shrimp', 'prawn', 'lobster', 'tuna', 'veal', 'emu', 'crab', 'mussel', 'oyster', 'sausage', 'scallop', 'clam', 'kangaroo', 'snapper', 'sardines', 'anchovy']

exc = ['planted-based', 'vegan']

veg = ['amaranth',
'barley',
'buckwheat',
'bulgar',
'cornmeal',
'couscous',
'farro',
'freekeh',
'kamut',
'millet',
'sorghum',
'spelt',
'wheat berries',
'acorn squash',
'artichoke hearts',
'asparagus',
'broccoli',
'brussels sprouts',
'cabbage',
'carrot',
'cauliflower',
'celery',
'cucumber',
'eggplant',
'mushroom',
'onion',
'peppers',
'radish',
'spaghetti squash',
'tomato',
'turnip',
'zucchini',
'arugula',
'bok choy',
'collard greens',
'kale',
'romaine',
'spinach',
'Swiss chard',
'Starchy veggies',
'beets',
'butternut squash',
'corn',
'parsnips',
'pumpkin',
'sweet potato',
'yam',
'corn', 'crookneck', 'cucumber', 'daikon', 'dandelion', 'edamame', 'lettuce', 'peas']

sau = ['pesto', 'sour cream', 'yellow mustard', 'mayo', 'alfredo sauce']